version: '3.8'

services:
  dabba:
    image: ghcr.io/trugamr/dabba:latest
    environment:
      - STACKS_DIRERCTORY=/app/stacks
    ports:
      - 6040:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ./stacks:/app/stacks
