version: '3.8'

services:
  dabba:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      - STACKS_DIRERCTORY=/app/stacks
    ports:
      - 8080:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ./stacks:/app/stacks
